---
--- Generated by Luanalysis
--- Created by lianMeng.
--- DateTime: 2023/5/16 20:34
---

--1 用户参数
--1.1 优惠券id
local voucherId = ARGV[1]
--1.2 用户id
local userId = ARGV[2]
--1.3 订单od
local orderId = ARGV[3]

--2. 数据key
--2.1 库存key    ..相当于java的+
local stockKey = 'seckill:stock' .. voucherId
--2.2 订单key
local orderKey = 'seckill:order' .. voucherId

--3. 脚本业务员
--3.1 判断是否还有库存   库存不足返回1
if (tonumber(redis.call('get',stockKey)) <= 0) then
    return 1
end

--3.2 判断用户是否下过单 sismember 判断set中是否有对应的成员
if(redis.call('sismember',orderKey,userId) == 1) then
    return 2
end

--3.3 对库存减一
redis.call('incrby',stockKey,-1)
--3.4 保存用户id
redis.call('sadd',orderKey,userId)
--3.6 发送消息  xadd stream.orders * k1 v1 v2 v3
redis.call('xadd','stream.orders','*','userId',userId, 'voucherId',voucherId,'id',orderId)

return 0